version: "3.4"
services:
  agora:
    build: ./apps/agora
    command: "yarn start"
    volumes:
      - ./apps/agora:/var/www
      - /var/www/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL
      - SECRET
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - postgres

  absinthe:
    build: ./apps/absinthe
    command: "yarn start"
    volumes:
      - ./apps/absinthe:/var/www
      - /var/www/node_modules
    environment:
      - POSTGRES_URL=${POSTGRES_MOCK_URL}
    depends_on:
      - postgres_mock

  sunwell:
    # temporary option in order webpack not to exit
    stdin_open: true
    build: ./apps/sunwell
    command: >
      bash -c "rm -rf /var/www/node_modules/@sourceface/style &&
               ln -s /mnt/style /var/www/node_modules/@sourceface/style &&
               yarn start"
    volumes:
      - ./apps/sunwell:/var/www
      - /var/www/node_modules
      - ./packages/style:/mnt/style
      - style_node_modules:/mnt/style/node_modules
    environment:
      - AGORA_HOST=${AGORA_HOST}
      - PORT=3001
    ports:
      - "3001:3001"

  # components:
  #   build: ./packages/components
  #   command: >
  #     bash -c "rm -rf /var/www/node_modules/react &&
  #              ln -s /mnt/sunwell/node_modules/react /var/www/node_modules/react &&
  #              rm -rf /var/www/node_modules/@sourceface/style &&
  #              ln -s /mnt/style /var/www/node_modules/@sourceface/style &&
  #              yarn start"
  #   volumes:
  #     - ./packages/components:/var/www
  #     - components_node_modules:/var/www/node_modules
  #     - ./packages/style:/mnt/style
  #     - style_node_modules:/mnt/style/node_modules
  #     - sunwell_node_modules:/mnt/sunwell/node_modules
  #   ports:
  #     - "4001:4001"

  style:
    build: ./packages/style
    command: "tail -f /dev/null"
    volumes:
      - ./packages/style:/var/www
      - style_node_modules:/var/www/node_modules

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  postgres_mock:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  style_node_modules:
