version: "3.4"
services:
  agora:
    build: ./apps/agora
    command: >
      bash -c "yarn install && yarn start"
    volumes:
      - ./apps/agora:/var/www
      - /var/www/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL
      - SECRET
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  sunwell:
    # temporary option in order webpack not to exit
    stdin_open: true
    build: ./apps/sunwell
    command: >
      bash -c "yarn install &&
               rm -rf /var/www/node_modules/@sourceface/components &&
               ln -s /mnt/components /var/www/node_modules/@sourceface/components &&
               rm -rf /var/www/node_modules/@sourceface/style &&
               ln -s /mnt/style /var/www/node_modules/@sourceface/style &&
               yarn start"
    volumes:
      - ./apps/sunwell:/var/www
      - /var/www/node_modules
      - ./packages/components:/mnt/components
      - components_node_modules:/mnt/components/node_modules
      - ./packages/style:/mnt/style
      - style_node_modules:/mnt/style/node_modules
    environment:
      - AGORA_HOST=${AGORA_HOST}
    ports:
      - "3000:3000"

  components:
    build: ./packages/components
    command: >
      bash -c "yarn install &&
               rm -rf /var/www/node_modules/@sourceface/style &&
               ln -s /mnt/style /var/www/node_modules/@sourceface/style &&
               yarn start"
    volumes:
      - ./packages/components:/var/www
      - components_node_modules:/var/www/node_modules
      - ./packages/style:/mnt/style
      - style_node_modules:/mnt/style/node_modules
    ports:
      - "4000:4000"

  style:
    build: ./packages/style
    command: "tail -f /dev/null"
    volumes:
      - ./packages/style:/var/www
      - style_node_modules:/var/www/node_modules

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  components_node_modules:
  style_node_modules:
