version: "3.4"
services:
  agora:
    build: ./apps/agora
    command: >
      bash -c "cd /mnt/schema && yarn link &&
               cd /var/www && yarn link @sourceface/schema &&
               yarn start"
    volumes:
      - ./apps/agora:/var/www
      - /var/www/node_modules
      - ./packages/schema:/mnt/schema
      - schema_node_modules:/mnt/schema/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5001
      - SUNWELL_HOST
      - SECRET
      - DATABASE_URL
      - POSTGRES_MOCK_URL
    ports:
      - "5001:5001"
    depends_on:
      - postgres

  absinthe:
    build: ./apps/absinthe
    command: "tail -f /dev/null"
    volumes:
      - ./apps/absinthe:/var/www
      - /var/www/node_modules
    environment:
      - POSTGRES_URL=${POSTGRES_MOCK_URL}
    depends_on:
      - postgres_mock

  sunwell:
    # temporary option in order webpack not to exit
    stdin_open: true
    build: ./apps/sunwell
    command: >
      bash -c "cd /mnt/style && yarn link &&
               cd /mnt/components && yarn link &&
               cd /mnt/schema && yarn link &&
               cd /var/www &&
               yarn link @sourceface/style @sourceface/components @sourceface/schema &&
               yarn start"
    volumes:
      - ./apps/sunwell:/var/www
      - /var/www/node_modules
      - ./packages/style:/mnt/style
      - style_node_modules:/mnt/style/node_modules
      - ./packages/components:/mnt/components
      - components_node_modules:/mnt/components/node_modules
      - ./packages/schema:/mnt/schema
      - schema_node_modules:/mnt/schema/node_modules
    environment:
      - NODE_ENV=development
      - AGORA_HOST
      - PORT=3001
    ports:
      - "3001:3001"

  components:
    build: ./packages/components
    command: >
      bash -c "cd /mnt/style && yarn link &&
               cd /var/www && yarn link @sourceface/style &&
               tail -f /dev/null"
    volumes:
      - ./packages/components:/var/www
      - components_node_modules:/var/www/node_modules
      - ./packages/style:/mnt/style
      - style_node_modules:/mnt/style/node_modules
    ports:
      - "4001:4001"

  schema:
    build: ./packages/schema
    command: "tail -f /dev/null"
    volumes:
      - ./packages/schema:/var/www
      - schema_node_modules:/var/www/node_modules

  style:
    build: ./packages/style
    command: "tail -f /dev/null"
    volumes:
      - ./packages/style:/var/www
      - style_node_modules:/var/www/node_modules

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  postgres_test:
    image: postgres:9.5
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  postgres_mock:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  style_node_modules:
  components_node_modules:
  schema_node_modules:
