version: "3.4"
services:
  agora:
    build: ./apps/agora
    command: "yarn start"
    volumes:
      - ./apps/agora:/var/www
      - /var/www/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL
      - SECRET
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  sunwell:
    # temporary option in order webpack not to exit
    stdin_open: true
    build: ./apps/sunwell
    command: >
      bash -c "rm -rf /var/www/node_modules/@sourceface/components &&
               ln -s /mnt/components /var/www/node_modules/@sourceface/components &&
               yarn start"
    volumes:
      - ./apps/sunwell:/var/www
      - /var/www/node_modules
      - ./packages/components:/mnt/components
    environment:
      - REACT_APP_AGORA_HOST=${AGORA_HOST}
    ports:
      - "3000:3000"

  # storybook
  components:
    build: ./packages/components
    command: "tail -f /dev/null"
    volumes:
      - ./packages/components:/var/www
      - /var/www/node_modules
    ports:
      - "4000:4000"

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
